[build]
  command = "pip install -r requirements.txt"
  publish = "public"
  functions = "netlify/functions"

[build.environment]
  PYTHON_VERSION = "3.12"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["telethon", "tweepy", "flask"]
  included_files = ["templates/**", "static/**"]

[functions.app]
  runtime = "python3.12"
  memory = 1024
  timeout = 30 